language: generic 

#sudo: required

services : 
  - docker

before_install:
  - docker build -t motaz/docker-react .

#script:
#  - docker run -e CI=true motaz/docker-react-app

deploy:
  provider: elasticbeanstalk
  region : "us-east-2"
  app : "test-motaz"
  env : "TestMotaz-env"
  bucket_name : "elasticbeanstalk-us-east-2-433534321141"
  bucket_path : "test-motaz"
  on:
      branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY