language: generic 

sudo: required

services : 
  - docker

before_install:
  - docker build -t motaz/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true motaz/docker-react-app npm run test -- --coverage